# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: postgres-csi
#   # namespace: superapp
#   namespace: app5
# spec:
#   provider: azure
#   secretObjects:
#   - secretName: pgpassword
#     type: Opaque
#     data:
#     - objectName: "pgpassword"
#       key: PGPASSWORD
#   parameters:
#     useVMManagedIdentity: "true"
#     userAssignedIdentityID: 29d34a2e-10da-4b36-9b4c-0e15c4e5a62c
#     keyvaultName: kv-app5akswik32dhm5i45tf # the name of the KeyVault
#     objects:  |
#       array:
#         - |
#           objectName: pgpassword
#           objectType: secret
#     tenantId: 449fbe1d-9c99-4509-9014-4fd5cf25b014 # the tenant ID of the KeyVault

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pgpasswordspc
  namespace: superapp
spec:
  parameters:
    clientID: 86957e6d-bfc4-4bba-bdb8-9b3c2c97a1d9
    keyvaultName: kv-appsuperappviipocxpkf
    objects: |
      array:
        - |
          objectName: pgpassword
          objectType: secret
    tenantId: 449fbe1d-9c99-4509-9014-4fd5cf25b014
  provider: azure
  secretObjects:
  - data:
    - key: pgpassword
      objectName: pgpassword
    secretName: pgpassword
    type: Opaque